// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSwEy6AGetkclb7XX6G_5aLLxua_sdPw',
    appId: '1:618749503113:web:568277fc2a40398c4ec858',
    messagingSenderId: '618749503113',
    projectId: 'telecare-doctor-task-2026',
    authDomain: 'telecare-doctor-task-2026.firebaseapp.com',
    storageBucket: 'telecare-doctor-task-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMR2neTMCtJORPzzutMFj7M2JBkHsVY0',
    appId: '1:618749503113:android:6e77a557e4adf39c4ec858',
    messagingSenderId: '618749503113',
    projectId: 'telecare-doctor-task-2026',
    storageBucket: 'telecare-doctor-task-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-AYZiT4y7pQruF0ubdtcB5cE64OcDbUI',
    appId: '1:618749503113:ios:f37c6098b7a533114ec858',
    messagingSenderId: '618749503113',
    projectId: 'telecare-doctor-task-2026',
    storageBucket: 'telecare-doctor-task-2026.firebasestorage.app',
    iosBundleId: 'com.example.telecareDoctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-AYZiT4y7pQruF0ubdtcB5cE64OcDbUI',
    appId: '1:618749503113:ios:f37c6098b7a533114ec858',
    messagingSenderId: '618749503113',
    projectId: 'telecare-doctor-task-2026',
    storageBucket: 'telecare-doctor-task-2026.firebasestorage.app',
    iosBundleId: 'com.example.telecareDoctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhSwEy6AGetkclb7XX6G_5aLLxua_sdPw',
    appId: '1:618749503113:web:a25326189bcc3e5c4ec858',
    messagingSenderId: '618749503113',
    projectId: 'telecare-doctor-task-2026',
    authDomain: 'telecare-doctor-task-2026.firebaseapp.com',
    storageBucket: 'telecare-doctor-task-2026.firebasestorage.app',
  );
}
